# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# SelectandClipbyArcPy.py
# Created: January 28th 2016
#   (generated by ArcGIS/ModelBuilder)
# Description: Select and Clip
# ---------------------------------------------------------------------------

# First make sure you make a folder connection in ArcMap
# to your working directory. This can be done via: Catalog -> right-click
# Folder Connections -> # Connect to folder... -> set your path.

# Import arcpy module
import arcpy
from arcpy import env
from select_and_clip import buildWhereClause
from select_and_clip import select_and_clip

# Set workspace: fill in your own path (the same as you did in ArcMap).
env.workspace = "E:\\Studie\\2015-2016-P3-GRS-33806\\data\\test2" # this is a Windows example

# Local input variables:
OSMinshpNLmun = "NLD_adm_shp\\NLD_adm2.shp"
OSMinshpNLroads = "osm\\roads.shp"
# Output variables:
SelectMun = "output\\mun.shp"
OSMinshpNLmunroads = "output\\munroads.shp"
# Municipality name you want to select and clip for:
Municipality = 'Wageningen'

# Run the function
select_and_clip(OSMinshpNLmun, OSMinshpNLroads, SelectMun, OSMinshpNLmunroads, Municipality)
